--- 
title: "Sustainable Ruminant Health"
author: 
  name: "[Ass. Prof. Miel M.P.G. Hostens](https://www.uu.nl/staff/MMHostens) and [Prof. dr. Theo J.G.M. Lam](https://www.uu.nl/medewerkers/TJGMLam)"
  affiliation: Utrecht University
  email: m.m.hostens@uu.nl
date: "Version compiled `r format(Sys.time(), '%d %b %Y')`"
description: "Textbook on Sustainable Ruminant Health, used in MSc in Veterinary Medicine at Utrecht University, the Netherlands." 
documentclass: book
github-repo: bovi-analytics/sustainableruminanthealth
link-citations: yes
bibliography:
- book.bib
- packages.bib
site: bookdown::bookdown_site
biblio-style: apalike
---

# Preface

TO DO

Utrecht, June 2021

Miel Hostens, <https://www.uu.nl/staff/MMHostens>

Theo Lam, <https://www.uu.nl/medewerkers/TJGMLam>

## License {-}

This document is licensed under the _GNU GPL 3_ license (for details see 
https://www.gnu.org/licenses/gpl-3.0.en.html). 

## Citation {-}

Please cite this work as follows (in APA style, and substitute the date):

Hostens, M. \& Lam, T. (2021). *Sustainable Ruminant Health*. 
Retrieved 29 January 2021 from <https://github.com/Bovi-analytics/SustainableRuminantHealth> .


## Contribution {-}

To contribute or use existing Open Educational Resources**

Another key advantage of using a GitBook is, that you can easily make your course materials available for others to use under an open access license, or perhaps you can use an existing GitBook from the internet and adapt it for your own uses. GitBooks can be easily duplicated and adapted, just like any other project hosted on GitHub. Contributing Open Educational Materials can help reduce the workload on teachers around the world, and can improve the quality of the materials used thanks to online collaborating and feedback.

```{r include=FALSE}
# automatically create a bib database for R packages
require(lattice)
require(nnet)
knitr::write_bib( c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```
